"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {ArrowLeft,BookOpen,Clock3,Download,RefreshCw,Users} from "lucide-react";
type Entry={student_id:string,day_number:number,ordinal:number,score:number,total:number,elapsed_seconds:number,submitted_at:string,student:{first_name:string,last_name:string,username:string}|null};
type P={id:string,day_number:number,ordinal:number,title:string,status:string};
const days=[1,5,8,12,15];
const dates=["1 October","5 October","8 October","12 October","15 October"];
function mins(s:number){return Math.floor(s/60)+"m "+String(s%60).padStart(2,"0")+"s"}
export default function ReadingAdmin(){
 const [day,setDay]=useState(1),[rows,setRows]=useState<Entry[]>([]),[passages,setPassages]=useState<P[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true),[unauthorized,setUnauthorized]=useState(false);
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/challenge-reading?action=admin&day="+day,{credentials:"same-origin",cache:"no-store"});const v=await r.json();if(!r.ok){setUnauthorized(r.status===401);throw Error(v.error||"Cannot load results")}setRows(v.attempts||[]);setPassages(v.passages||[])}catch(e){setError(String(e))}finally{setLoading(false)}}
 useEffect(()=>{load()},[day]);
 const groups=useMemo(()=>{const map=new Map<string,{student:Entry["student"],p1?:Entry,p2?:Entry}>();for(const r of rows){let x=map.get(r.student_id);if(!x){x={student:r.student};map.set(r.student_id,x)}if(r.ordinal===1)x.p1=r;else x.p2=r;}return [...map.values()].sort((a,b)=>(b.p1?.score||0)+(b.p2?.score||0)-(a.p1?.score||0)-(a.p2?.score||0))},[rows]);
 const totalSeconds=rows.reduce((n,r)=>n+r.elapsed_seconds,0);
 function exportCSV(){const table=[["Student","Username","Day","Passage 1 score","Passage 1 time","Passage 2 score","Passage 2 time","Total score","Total time"],...groups.map(g=>[g.student?.first_name+" "+g.student?.last_name,g.student?.username,String(day),g.p1?g.p1.score+"/"+g.p1.total:"",g.p1?mins(g.p1.elapsed_seconds):"",g.p2?g.p2.score+"/"+g.p2.total:"",g.p2?mins(g.p2.elapsed_seconds):"",String((g.p1?.score||0)+(g.p2?.score||0)),mins((g.p1?.elapsed_seconds||0)+(g.p2?.elapsed_seconds||0))])];const contents=table.map(line=>line.map(v=>'"'+String(v||"").replaceAll('"','""')+'"').join(",")).join("\n");const blob=new Blob(["\ufeff"+contents],{type:"text/csv;charset=utf-8"});const u=URL.createObjectURL(blob);const a=document.createElement("a");a.href=u;a.download="ark-reading-day-"+day+".csv";a.click();URL.revokeObjectURL(u);}
 return <main className="cr-admin"><header><Link href="/admin"><ArrowLeft size={17}/> Admin panel</Link><strong>ARK EDUCATION · READING REPORTS</strong><button onClick={load}><RefreshCw size={15}/> Refresh</button></header><section className="cr-a-content"><div className="cr-a-heading"><div><small>60-DAY CHALLENGE · LIVE RESULTS</small><h1>Reading reports</h1><p>View students' individual passage scores, completion dates and elapsed time.</p></div><button onClick={exportCSV} disabled={!rows.length}><Download size={16}/> Export CSV</button></div>
 <div className="cr-a-days">{days.map((n,i)=><button key={n} className={n===day?"selected":""} onClick={()=>setDay(n)}><span>Day {String(n).padStart(2,"0")}</span><b>{dates[i]}</b></button>)}</div>
 <div className="cr-a-stats"><div><Users/><small>Students who submitted</small><strong>{groups.length}</strong></div><div><BookOpen/><small>Passages completed</small><strong>{rows.length}</strong></div><div><Clock3/><small>Total recorded time</small><strong>{mins(totalSeconds)}</strong></div></div>
 <section className="cr-a-table"><h2>Day {day} · {passages.map(x=>x.title).join(" / ")}</h2>{error&&<p className="cr-a-error">{error}{unauthorized&&<> · <Link href="/admin">Sign in</Link></>}</p>}{loading?<p className="cr-a-empty">Loading real results…</p>:!rows.length?<p className="cr-a-empty">No students have submitted reading passages for this day yet.</p>:<div className="cr-a-overflow"><table><thead><tr><th>Student</th><th>Passage 1</th><th>Passage 2</th><th>Total</th><th>Time</th><th>Submitted</th></tr></thead><tbody>{groups.map((g,i)=><tr key={i}><td><b>{g.student?.first_name} {g.student?.last_name}</b><small>@{g.student?.username}</small></td><td>{g.p1?<><b>{g.p1.score}/{g.p1.total}</b><small>{mins(g.p1.elapsed_seconds)}</small></>:"Not submitted"}</td><td>{g.p2?<><b>{g.p2.score}/{g.p2.total}</b><small>{mins(g.p2.elapsed_seconds)}</small></>:"Not submitted"}</td><td><b>{(g.p1?.score||0)+(g.p2?.score||0)}/{(g.p1?.total||0)+(g.p2?.total||0)}</b></td><td>{mins((g.p1?.elapsed_seconds||0)+(g.p2?.elapsed_seconds||0))}</td><td>{g.p2?.submitted_at||g.p1?.submitted_at?new Date((g.p2||g.p1)!.submitted_at).toLocaleString("en-GB",{timeZone:"Asia/Tashkent",dateStyle:"medium",timeStyle:"short"}):"—"}</td></tr>)}</tbody></table></div>}</section>
 </section><style jsx global>{`
 body{margin:0}.cr-admin{min-height:100vh;background:#f7f8fb;color:#192335;font:14px Arial,sans-serif}.cr-admin header{height:65px;background:white;border-bottom:1px solid #e5e9f0;display:flex;justify-content:space-between;align-items:center;padding:0 32px}.cr-admin header a{display:flex;align-items:center;gap:7px;text-decoration:none;color:#4c5667}.cr-admin header strong{font-size:12px;letter-spacing:.09em}.cr-admin button{cursor:pointer}.cr-admin header button,.cr-a-heading button{display:flex;align-items:center;gap:7px;background:white;border:1px solid #dce1e8;padding:10px 15px;border-radius:8px;font-weight:bold}.cr-a-content{max-width:1220px;margin:38px auto;padding:0 18px}.cr-a-heading{display:flex;justify-content:space-between;align-items:center;gap:15px;margin:0 0 28px}.cr-a-heading small{color:#d83647;font-weight:bold;letter-spacing:.1em}.cr-a-heading h1{font-size:32px;margin:8px 0}.cr-a-heading p{margin:0;color:#677589}.cr-a-days{display:flex;gap:9px;flex-wrap:wrap;margin-bottom:22px}.cr-a-days button{border:1px solid #e1e5eb;border-radius:10px;background:white;padding:13px 18px;text-align:left;min-width:145px}.cr-a-days button span{display:block;font-size:10px;color:#718198;margin-bottom:6px}.cr-a-days button b{font-size:14px}.cr-a-days button.selected{border-color:#303b54;background:#f0f3fb}.cr-a-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:13px}.cr-a-stats>div{background:white;border:1px solid #e5e8ed;border-radius:11px;padding:20px;display:flex;flex-direction:column;align-items:start;gap:8px}.cr-a-stats svg{color:#677b9a}.cr-a-stats small{color:#718198}.cr-a-stats strong{font-size:28px}.cr-a-table{margin-top:22px;background:white;border:1px solid #e2e6eb;border-radius:13px;padding:21px}.cr-a-table h2{font-size:17px}.cr-a-overflow{overflow-x:auto}.cr-a-table table{border-collapse:collapse;width:100%;min-width:700px;margin-top:18px;text-align:left}.cr-a-table th{font-size:11px;color:#7c8899;border-bottom:1px solid #e5eaf0;padding:14px 12px}.cr-a-table td{padding:17px 12px;border-bottom:1px solid #f0f1f5}.cr-a-table td small{display:block;color:#8993a3;font-size:11px;margin-top:5px}.cr-a-empty{padding:28px;text-align:center;color:#64748b}.cr-a-error{background:#fff1f1;padding:12px;color:#9e2020}@media(max-width:680px){.cr-admin header{padding:0 12px}.cr-admin header strong{display:none}.cr-a-heading h1{font-size:26px}.cr-a-stats{grid-template-columns:1fr}.cr-a-stats>div{padding:12px}.cr-a-stats strong{font-size:22px}.cr-a-table{padding:12px}}
 `}</style></main>;
}