"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {ArrowLeft,CheckCircle2,Clock3,FileText,RefreshCcw,Search,Send,UserRound} from "lucide-react";
import "./writing-admin.css";
type Row={id:string;day_number:number;payload:any;submitted_at:string;band:number|null;review_status:string;review_feedback?:string|null;reviewed_at?:string|null;student:{first_name:string;last_name:string;username:string}|null};
export default function AdminWriting(){
 const [rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 const [query,setQuery]=useState(""),[filter,setFilter]=useState<"pending"|"checked"|"all">("pending");
 const [bands,setBands]=useState<Record<string,string>>({}),[feedback,setFeedback]=useState<Record<string,string>>({}),[busy,setBusy]=useState("");
 async function load(){setLoading(true);setMessage("");try{const res=await fetch("/api/challenge-writing?action=admin_list",{credentials:"same-origin",cache:"no-store"});const obj=await res.json();if(!res.ok){setMessage(obj.detail||"Could not load Writing submissions.");return}setRows(obj.submissions||[]);const b:Record<string,string>={},f:Record<string,string>={};(obj.submissions||[]).forEach((r:Row)=>{if(r.band!==null)b[r.id]=String(r.band);if(r.review_feedback)f[r.id]=r.review_feedback});setBands(b);setFeedback(f)}catch{setMessage("Could not contact the server.")}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const visible=useMemo(()=>rows.filter(r=>filter==="all"||r.review_status===(filter==="checked"?"reviewed":filter)).filter(r=>{const s=(r.student?(r.student.first_name+" "+r.student.last_name+" "+r.student.username):"")+" "+r.day_number+" "+String(r.payload?.task_type||"");return s.toLowerCase().includes(query.trim().toLowerCase())}),[rows,filter,query]);
 const pending=rows.filter(r=>r.review_status==="pending").length;
 async function grade(row:Row){const band=Number(bands[row.id]);if(!Number.isFinite(band)){setMessage("Select a band score first.");return}setBusy(row.id);setMessage("");try{const res=await fetch("/api/challenge-writing",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({action:"grade",id:row.id,band,feedback:feedback[row.id]||""})});const obj=await res.json();if(!res.ok){setMessage(obj.detail||"Could not save score.");return}await load()}catch{setMessage("Could not contact the server.")}finally{setBusy("")}}
 return <main className="wa-shell"><header className="wa-top"><Link href="/admin"><ArrowLeft size={17}/> Admin</Link><div><b>ARK EDUCATION</b><span>WRITING INBOX</span></div><button onClick={load}><RefreshCcw size={15}/> Refresh</button></header>
 <section className="wa-hero"><div><small>60 DAY IELTS CHALLENGE</small><h1>Writing submissions</h1><p>Open each PDF, review the response, assign an IELTS band, and optionally leave feedback.</p></div><div className="wa-kpis"><span><b>{pending}</b> Pending</span><span><b>{rows.length-pending}</b> Checked</span><span><b>{rows.length}</b> Total</span></div></section>
 <section className="wa-toolbar"><div className="wa-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search student, day or task…"/></div><div className="wa-tabs">{(["pending","checked","all"] as const).map(x=><button key={x} className={filter===x?"active":""} onClick={()=>setFilter(x)}>{x}</button>)}</div></section>
 {message&&<p className="wa-message">{message}</p>}<section className="wa-list">{loading?<div className="wa-empty">Loading submissions…</div>:visible.length===0?<div className="wa-empty"><FileText size={28}/><b>No Writing submissions here.</b></div>:visible.map(row=>{const name=row.student?(row.student.first_name+" "+row.student.last_name):"Student";const checked=row.review_status==="reviewed";return <article className={"wa-card "+(checked?"checked":"")} key={row.id}><div className="wa-card-head"><span className="wa-avatar"><UserRound size={18}/></span><div><h2>{name}</h2><p>@{row.student?.username||"student"} · Day {String(row.day_number).padStart(2,"0")} · {String(row.payload?.task_type||"writing").toUpperCase()}</p></div><span className={"wa-state "+(checked?"done":"wait")}>{checked?<CheckCircle2 size={14}/>:<Clock3 size={14}/>} {checked?"Checked":"Pending review"}</span></div>
 <div className="wa-metrics"><span><small>WORDS</small><b>{row.payload?.word_count??"—"}</b></span><span><small>TIME</small><b>{Math.floor(Number(row.payload?.duration_seconds||0)/60)}m {String(Number(row.payload?.duration_seconds||0)%60).padStart(2,"0")}s</b></span><span><small>SUBMITTED</small><b>{new Date(row.submitted_at).toLocaleString("en-GB",{timeZone:"Asia/Tashkent",day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"})}</b></span><a href={"/api/challenge-writing?action=pdf&id="+row.id} target="_blank" rel="noreferrer"><FileText size={15}/> Open PDF</a></div>
 <div className="wa-review"><label><span>IELTS Band</span><select value={bands[row.id]||""} onChange={e=>setBands(v=>({...v,[row.id]:e.target.value}))}><option value="">Select</option>{Array.from({length:19},(_,i)=>i/2).map(v=><option key={v} value={v}>{v.toFixed(1)}</option>)}</select></label><label className="feedback"><span>Feedback <i>optional</i></span><textarea value={feedback[row.id]||""} onChange={e=>setFeedback(v=>({...v,[row.id]:e.target.value}))} placeholder="Short teacher feedback for the student…"/></label><button disabled={busy===row.id||!bands[row.id]} onClick={()=>grade(row)}>{busy===row.id?"Saving…":checked?"Update result":"Save score"}<Send size={15}/></button></div></article>})}</section></main>;
}