"use client";
import Link from "next/link";
import ArkWordmark from "../components/ark-wordmark";
import {useEffect,useState} from "react";
import {LayoutDashboard,Users,CalendarDays,FileText,Mic,ChartNoAxesCombined,Trophy,Clock3,Settings,BookOpen,Headphones,Newspaper,NotebookPen,PenLine,Bell,Menu,X,ShieldCheck,ChevronRight,UploadCloud,CheckCircle2,LockKeyhole,ClipboardCheck,Search,GraduationCap,LogOut} from "lucide-react";

const sections=[{name:"Overview",icon:LayoutDashboard},{name:"Students",icon:Users},{name:"Content manager",icon:CalendarDays},{name:"Writing inbox",icon:FileText},{name:"Speaking inbox",icon:Mic},{name:"Results",icon:ChartNoAxesCombined},{name:"Leaderboard",icon:Trophy},{name:"Study time",icon:Clock3},{name:"Settings",icon:Settings}];
const courseDays=Array.from({length:60},(_,i)=>{const d=new Date(Date.UTC(2026,9,i+1));return {n:i+1,date:d,mock:d.getUTCDay()===0}});
const contentModules=[{name:"Reading",icon:BookOpen,desc:"2 academic passages + answer keys"},{name:"Listening",icon:Headphones,desc:"Full listening test + audio + transcript"},{name:"Article",icon:Newspaper,desc:"CDI academic article + comprehension"},{name:"Vocabulary",icon:NotebookPen,desc:"Daily B2–C1 set and quiz"},{name:"Writing",icon:PenLine,desc:"Task 1 / Task 2 alternating"},{name:"Speaking",icon:Mic,desc:"Practice prompts + browser recording"}];
export default function Admin(){
 const [view,setView]=useState("Overview");
 const [selected,setSelected]=useState(1);
 const [mobile,setMobile]=useState(false);
 const [clock,setClock]=useState("");
 useEffect(()=>{function tick(){setClock(new Intl.DateTimeFormat("en-GB",{timeZone:"Asia/Tashkent",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).format(new Date()))}tick();const id=setInterval(tick,1000);return()=>clearInterval(id)},[]);
 const chosen=courseDays[selected-1];
 const items=chosen.mock?[contentModules[1],contentModules[0],contentModules[4],contentModules[5]]:contentModules;
 return <div className="learning-shell admin-v2">
  <aside className={"learning-sidebar "+(mobile?"open":"")}><div className="learning-brand"><ArkWordmark subtitle="ADMIN WORKSPACE"/><button className="mobile-close" onClick={()=>setMobile(false)} aria-label="Close navigation"><X size={18}/></button></div><div className="side-overline">MANAGEMENT</div><nav className="learning-nav">{sections.map(({name,icon:Icon})=><button key={name} className={view===name?"active":""} onClick={()=>{setView(name);setMobile(false)}}><Icon size={18} strokeWidth={1.8}/><span>{name}</span>{view===name&&<ChevronRight size={14}/>}</button>)}</nav><div className="sidebar-bottom"><div className="side-promo"><ShieldCheck size={19}/><b>Preview mode</b><p>Student information and private submissions appear only after the protected backend is activated.</p></div><Link className="back-login" href="/"><LogOut size={15}/> Back to sign in</Link><div className="user-tile"><span className="user-avatar">AD</span><div><b>Admin preview</b><small>ARK Education</small></div></div></div></aside>
  {mobile&&<button className="sidebar-overlay" onClick={()=>setMobile(false)} aria-label="Close navigation"/>}
  <div className="learning-main"><header className="learning-topbar"><div className="topbar-left"><button className="menu-toggle" aria-label="Open navigation" onClick={()=>setMobile(true)}><Menu size={20}/></button><b className="topbar-section">{view}</b><div className="topbar-line"/><span className="topbar-status"><span className="status-pulse"/> Course starts 1 October</span></div><div className="topbar-right"><span className="time-chip"><Clock3 size={15}/>{clock||"--:--:--"} <small>UZT</small></span><button className="top-icon" onClick={()=>setView("Notifications")} aria-label="Notifications"><Bell size={18}/></button><span className="profile-chip"><span>AD</span> Admin preview</span></div></header>
   <main className="learning-content"><div className="page-heading"><div><div className="section-eyebrow"><GraduationCap size={17}/> ADMINISTRATION <span className="eyebrow-line"/></div><h1>{view==="Overview"?"Course control centre":view}</h1><p>ARK IELTS · 60-day challenge · 1 October – 29 November 2026</p></div><span className="date-badge"><ShieldCheck size={16}/> PREVIEW MODE</span></div>
   {view==="Overview"?<>
    <div className="kpi-row"><div className="kpi-card"><div><span>REGISTERED STUDENTS</span><b>—</b><small>Awaiting secure registration</small></div><Users size={22}/></div><div className="kpi-card"><div><span>ACTIVE STUDY HOURS</span><b>—</b><small>Starts with student tracking</small></div><Clock3 size={22}/></div><div className="kpi-card"><div><span>WRITING TO REVIEW</span><b>0</b><small>No submissions yet</small></div><FileText size={22}/></div><div className="kpi-card kpi-highlight"><div><span>SPEAKING TO REVIEW</span><b>0</b><small>No recordings yet</small></div><Mic size={22}/></div></div>
    <div className="study-layout"><section className="calendar-panel"><div className="panel-title-row"><div><div className="section-eyebrow">COURSE STRUCTURE</div><h2>60-day content manager</h2><p>Preview every day and prepare material before its release date.</p></div><button className="admin-inline-btn" onClick={()=>setView("Content manager")}>Manage content <ChevronRight size={15}/></button></div><div className="admin-day-strip">{courseDays.map(d=><button key={d.n} onClick={()=>setSelected(d.n)} className={(selected===d.n?"picked ":"")+(d.mock?"mock":"")}><span>DAY {String(d.n).padStart(2,"0")}</span><b>{d.date.toLocaleDateString("en-GB",{timeZone:"UTC",day:"numeric",month:"short"})}</b><small>{d.mock?"MOCK":"6 MODULES"}</small></button>)}</div><div className="admin-shortcuts"><button onClick={()=>setView("Students")}><Users size={19}/><b>Student management</b><ChevronRight size={15}/></button><button onClick={()=>setView("Study time")}><Clock3 size={19}/><b>Study time reports</b><ChevronRight size={15}/></button><button onClick={()=>setView("Writing inbox")}><FileText size={19}/><b>Writing feedback</b><ChevronRight size={15}/></button><button onClick={()=>setView("Speaking inbox")}><Mic size={19}/><b>Speaking feedback</b><ChevronRight size={15}/></button></div></section><aside className="detail-panel"><div className="day-details-top"><div className="detail-overline">ADMIN · {chosen.mock?"SUNDAY MOCK":"DAILY LEARNING"}</div><div className="day-row"><h2>Day {String(chosen.n).padStart(2,"0")}</h2><span className="detail-status locked">No content</span></div><p>{chosen.date.toLocaleDateString("en-GB",{timeZone:"UTC",weekday:"long",day:"numeric",month:"long"})}</p><div className="detail-subhead"><span>{items.length} module slots</span><span>Upload later</span></div></div><div className="detail-list">{items.map(({name,icon:Icon,desc})=><div className="detail-item" key={name}><span className="task-icon purple"><Icon size={18}/></span><div className="task-copy"><strong>{name}</strong><small>{desc}</small></div><span className="task-action">Draft</span></div>)}</div><div className="day-detail-footer"><div><span>RELEASE RULE</span><b>Unlocks on its calendar date</b></div><button className="detail-btn" onClick={()=>setView("Content manager")}>Open content manager <ChevronRight size={16}/></button></div></aside></div>
    <div className="bottom-insights"><article><div className="insight-icon"><Clock3 size={20}/></div><div><b>Real study-time reporting</b><p>Once connected, admin will see each student's daily, weekly, total and per-module active hours, including CDI articles.</p></div></article><article><div className="insight-icon"><ShieldCheck size={20}/></div><div><b>Protected student records</b><p>Coin history, writing feedback, speaking recordings and login records require authenticated admin access.</p></div></article></div>
   </>:view==="Content manager"?<section className="calendar-panel admin-full"><div className="panel-title-row"><div><div className="section-eyebrow">CONTENT LIBRARY</div><h2>Prepare 60 course days</h2><p>Select a day to inspect its required slots. Files can be uploaded once the backend is connected.</p></div></div><div className="admin-day-strip">{courseDays.map(d=><button key={d.n} onClick={()=>setSelected(d.n)} className={(selected===d.n?"picked ":"")+(d.mock?"mock":"")}><span>DAY {String(d.n).padStart(2,"0")}</span><b>{d.date.toLocaleDateString("en-GB",{timeZone:"UTC",day:"numeric",month:"short"})}</b><small>{d.mock?"MOCK":"6 MODULES"}</small></button>)}</div><div className="admin-upload-grid">{items.map(({name,icon:Icon,desc})=><div className="admin-upload-card" key={name}><Icon size={22}/><h3>{name}</h3><p>{desc}</p><span>Upload available after content storage setup</span></div>)}</div></section>:<section className="empty-view admin-empty"><div className="empty-icon">{view==="Study time"?<Clock3 size={30}/>:view==="Students"?<Users size={30}/>:view==="Leaderboard"?<Trophy size={30}/>:view==="Writing inbox"?<FileText size={30}/>:view==="Speaking inbox"?<Mic size={30}/>:<Settings size={30}/>}</div><h1>{view}</h1><p>{view==="Study time"?"Active study time will be tracked automatically in Reading, Listening, Article, Vocabulary, Writing and Speaking after students activate accounts.":view==="Students"?"Manage invitation codes and student target bands after secure accounts are enabled.":"Private student data and the live workflow will appear here after secure database connection."}</p><button onClick={()=>setView("Overview")}>Return to overview <ChevronRight size={17}/></button></section>}
   </main>
  </div>
 </div>;
}