"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {ArrowLeft,Bell,CheckCircle2,Clock3,MessageSquareText,PenLine} from "lucide-react";
import "./notifications.css";
type Note={id:string;day_number:number;payload:any;band:number|null;review_feedback?:string|null;reviewed_at?:string|null;submitted_at:string;review_status:string};
export default function Notifications(){
 const [items,setItems]=useState<Note[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 useEffect(()=>{let live=true;(async()=>{try{const res=await fetch("/api/challenge-writing?action=notifications",{credentials:"same-origin",cache:"no-store"});const obj=await res.json();if(!res.ok){if(live)setMessage(obj.detail||"Could not load notifications.");return}if(live)setItems(obj.notifications||[])}catch{if(live)setMessage("Could not contact the server.")}finally{if(live)setLoading(false)}})();return()=>{live=false}},[]);
 return <main className="nt-shell"><header className="nt-top"><Link href="/dashboard"><ArrowLeft size={17}/> Dashboard</Link><b>ARK EDUCATION</b><span><Bell size={17}/> Notifications</span></header><section className="nt-head"><small>STUDENT UPDATES</small><h1>Notifications</h1><p>Your checked Writing results appear here as soon as your teacher saves the band score.</p></section><section className="nt-list">{loading?<div className="nt-empty">Loading…</div>:message?<div className="nt-empty">{message}</div>:items.length===0?<div className="nt-empty"><Bell size={28}/><b>No new Writing results yet.</b><p>Checked results will appear here automatically.</p></div>:items.map(n=><article className="nt-card" key={n.id}><span className="nt-icon"><PenLine size={20}/></span><div className="nt-copy"><div className="nt-row"><small>WRITING RESULT · DAY {String(n.day_number).padStart(2,"0")}</small><span><Clock3 size={12}/>{n.reviewed_at?new Date(n.reviewed_at).toLocaleString("en-GB",{timeZone:"Asia/Tashkent",day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}):"Checked"}</span></div><h2>{String(n.payload?.task_type||"Writing").toUpperCase()} checked</h2><p>Your Writing response has been reviewed.</p>{n.review_feedback&&<div className="nt-feedback"><MessageSquareText size={15}/><span>{n.review_feedback}</span></div>}<Link href={"/day/"+n.day_number+"/writing"}>View result <CheckCircle2 size={14}/></Link></div><div className="nt-band"><small>BAND</small><b>{Number(n.band).toFixed(1)}</b></div></article>)}</section></main>;
}